apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build
spec:
  workspaces:
  - name: source
  params:
  - name: imageUrl
    type: string
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:v1.6.0
    args:
    - --dockerfile=$(workspaces.source.path)/Dockerfile
    - --destination=$(params.imageUrl)
    - --context=$(workspaces.source.path)
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    volumeMounts:
    - name: docker-config
      mountPath: /tekton/home/.docker
  volumes:
  - name: docker-config
    secret:
      secretName: dockerhub-credentials

