version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: railsuser
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:setup && rails s -b '0.0.0.0'"
    ports:
      - "3002:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://railsuser:securepassword@db:5432
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
