apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-rails-app
spec:
  params:
    - name: repo-url
      type: string
    - name: image-url
      type: string
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.repo-url)
    - name: build-push
      runAfter: ["clone"]
      taskRef:
        name: kaniko-build
      params:
        - name: imageUrl
          value: $(params.image-url)
        - name: CONTEXT
          value: /workspace/source

